# Generated by Django 4.0.6 on 2022-08-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imgNoticia',
            field=models.ImageField(null=True, upload_to='noticias'),
        ),
    ]
